spring:
  application:
    name: Student-Management-System
  datasource:
        url: jdbc:postgresql://localhost:5432/sms
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: MySecretKeyForJWTTokenGenerationThatIsAtLeast256BitsLongForHS256AlgorithmToWorkProperly
  expiration: 86400000

admin:
  password: prakashmalla@123
  email: praksashmalla@gmail.com