spring:
  application:
    name: Student-Management-System
  datasource:
        url: jdbc:postgresql://localhost:5432/sms
        username: postgres
        password: password
        driver-class-name: org.postgresql.Driver
        hikari:
          maximum-pool-size: 10
          minimum-idle: 5
          idle-timeout: 30000
          max-lifetime: 1800000
          connection-timeout: 30000
          pool-name: MyHikariCP
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: q8ZpQJ7xN9K2Fh3T6bW4R0YcS5mE1DVaLkXH2ZrUoM=
  expiration: 86400000

admin:
  password: prakashmalla@123
  email: praksashmalla@gmail.com

server:
  url: http://10.7.1.129:8080
  port: 8080


